### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by AndreySurzhan** [AndreySurzhan/ChecklistSLApi#13]
Request should return proper error when it fails
404,
500,
503,
401,
422 etc

**Comment by Sh1karno** [comment]
Tiket must be return in development becouse not all testes have been passed

**Comment by Sh1karno** [comment]
**Link to test result**
- https://docs.google.com/spreadsheets/d/12BJOIJsfiUryC8MtkO34L27RucRSX__Z1oq-3zztMTA/edit#gid=0

**Comment by AndreySurzhan** [comment]
I posted notes to the checklist with tests and submitted additional commits with fixes. should be ready for retest

**Comment by Sh1karno** [comment]
Retest successful, ticket can be closed

Link to test result
- https://docs.google.com/spreadsheets/d/12BJOIJsfiUryC8MtkO34L27RucRSX__Z1oq-3zztMTA/edit#gid=0

Remark is displayed on the ticket #27
