### ISSUE TITLE
High - checklist gets deleted with 500 Error

### ISSUE THREAD

**Issue by Gromoff9999** [AndreySurzhan/ChecklistSLApi#29]
**Environment**: 
https://qachecklistsl-web.herokuapp.com/
**Branches:**
qachecklish-api: remove-user-patch
qachecklist-web: master

**PC**: 
User should be registred and Login

**STEPS**:
1. Click: create checklist
2. Click button "Delete" checklist

**ACTUAL RESULT**: 
1. Checklist doesn't delete after click button "Delete". 500 Internal Server Error. 
2. Checklist does delete after refresh page.

**EXPECTED RESULT**:
Checklist should be delete after click "Delete" button

![2020-06-03_18-50-34](https://user-images.githubusercontent.com/66034726/83658907-8108c080-a5cb-11ea-8e93-8e23c035db7f.png)

**Log File**: 
[qachecklistsl-api-logs-1591199672065.txt](https://github.com/AndreySurzhan/ChecklistSLApi/files/4724547/qachecklistsl-api-logs-1591199672065.txt)

**Comment by Gromoff9999** [comment]
**Bug** reproduced on **environment**: _https://checklistsl-web.herokuapp.com/_
**Branch**: _ChecklistSLWebUi master_

**Comment by Sh1karno** [comment]
@Gromoff9999 Check this bug on **refert-patch-user** branch

**Comment by Gromoff9999** [comment]
****Retest on branch 79b43111**
_Impossible to delete checklist. Error 500._

**Regression**
_1. Possible to delete checklist if use instrument "Postman". 
If use Delete method-status 200 OK.
2. Possible delete checklist if use UI._

**Test result**
_AR=ER. Bug can be closed._
