### ISSUE TITLE
[Reopened] High - Impossible to save language 404 Error

### ISSUE THREAD

**Issue by Gromoff9999** [AndreySurzhan/ChecklistSLApi#30]
**_Environment_**: https://checklistsl-web.herokuapp.com/

Branch: master

**_PC_**: 
 User should be registrated and login.

**_Steps_**:
User should choose language.

**_Actual result_**:
1. After choose language 404 Error.
2. Translation items impossible
3. Languages doesn't choose after refresh page

![2020-06-07_13-39-15](https://user-images.githubusercontent.com/66034726/83966752-d511ee80-a8c4-11ea-98d7-790f8950ecb5.png)

**_Expected result_**:
Items should be translate according choosed languages

**_Application Logs:_**
[Log File.txt](https://github.com/AndreySurzhan/ChecklistSLApi/files/4741928/Log.File.txt)

**Comment by Sh1karno** [comment]
@Gromoff9999 Check this bug on **refert-patch-user** branch in QA enviroment please

**Comment by Gromoff9999** [comment]
Bug was checked on refert-patch-user branch in QA environment. Bug wasn't reproduce. 
Ticket should be close.

**Comment by Gromoff9999** [comment]
**Retest**
Impossible to save language.

**Regression**
1.Possible to choose language
2.Languages should be save
3.Items should be translate according selected languages.

**Test Result:**
AR=ER. Bug can be closed.
