### ISSUE TITLE
Test API

### ISSUE THREAD

**Issue by Sh1karno** [AndreySurzhan/ChecklistSLApi#32]
https://docs.google.com/spreadsheets/d/12BJOIJsfiUryC8MtkO34L27RucRSX__Z1oq-3zztMTA/edit#gid=0

**Comment by Gromoff9999** [comment]
Test run was pass.

**Environment:**

https://checklistsl-api.herokuapp.com/api

**Result:**
Bug: AndreySurzhan/ChecklistSLApi/issues/29

**Test run:**
https://docs.google.com/spreadsheets/d/12BJOIJsfiUryC8MtkO34L27RucRSX__Z1oq-3zztMTA/edit#gid=0

Ticket can be closed

**Comment by Sh1karno** [comment]
**Task verivied**
