### ISSUE TITLE
Create GetLanguages enpoint

### ISSUE THREAD

**Issue by AndreySurzhan** [AndreySurzhan/ChecklistSLApi#36]

**Comment by Gromoff9999** [comment]
### Test PASS.

###  RETEST:
_1. Possible to get full list of Languages by logged in User with GET method request - PASS.
2. Impossible to get full list of Languages by unlogged in User with GET method request   - PASS.
3. Impossible to get full list of Languages by logged in User and invalid URL with GET method request - PASS._


### Test result:
_AR=ER. Issue can be closed._
