### ISSUE TITLE
Fill languages data into new Static DB collection

### ISSUE THREAD

**Issue by AndreySurzhan** [AndreySurzhan/ChecklistSLApi#37]
Source https://github.com/AndreySurzhan/ChecklistSLWebUi/blob/master/src/utils/enums.js

1. Create Collections "Languages"
2. fill that collection with languages
- name 
- code
- Audit fields (createdOn  etc)

Created script for filling db in

**Comment by Gromoff9999** [comment]
### Collection languages created in DB.

**Environment:**
https://www.mlab.com/databases/heroku_f8v29mtz/collections/languages
Collection filled with languages.
**Instrument:**
https://tech.yandex.com/translate/doc/dg/concepts/api-overview-docpage/#api-overview__languages

Ticket can be closed.
